"use client";

// 📚 ADMIN: CREATE NEW EXAM PAGE
// Admin picks a syllabus, sets title/duration/date,
// then clicks "Generate Questions" — Gemini creates them automatically.

import { useState, useEffect } from "react";
import Sidebar from "@/components/Sidebar";
import { useRouter } from "next/navigation";
import { LayoutDashboard, BookOpen, FileText, BarChart3, Loader2, Brain, CheckCircle } from "lucide-react";

const navItems = [
  { label: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard },
  { label: "Syllabi", href: "/admin/syllabus", icon: FileText },
  { label: "Exams", href: "/admin/exams", icon: BookOpen },
  { label: "Analytics", href: "/admin/analytics", icon: BarChart3 },
];

export default function NewExamPage() {
  const router = useRouter();
  const [syllabi, setSyllabi] = useState<any[]>([]);
  const [form, setForm] = useState({
    title: "", syllabusId: "", duration: "60",
    scheduledAt: "", mcqCount: "5", codingCount: "3", difficulty: "medium",
  });
  const [step, setStep] = useState<"form" | "generating" | "done">("form");
  const [examId, setExamId] = useState("");
  const [log, setLog] = useState<string[]>([]);
  const [error, setError] = useState("");

  // Fetch available syllabi when page loads
  useEffect(() => {
    fetch("/api/syllabus").then((r) => r.json()).then(setSyllabi);
  }, []);

  const addLog = (msg: string) => setLog((l) => [...l, msg]);

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    setStep("generating");
    setLog([]);
    setError("");

    try {
      // Step 1: Create the exam record
      addLog("📝 Creating exam record...");
      const examRes = await fetch("/api/exams", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: form.title,
          syllabusId: form.syllabusId,
          duration: form.duration,
          scheduledAt: form.scheduledAt,
        }),
      });
      const exam = await examRes.json();
      setExamId(exam.id);
      addLog(`✅ Exam "${exam.title}" created`);

      // Step 2: Generate MCQ questions
      if (parseInt(form.mcqCount) > 0) {
        addLog(`🤖 Generating ${form.mcqCount} MCQ questions with Gemini AI...`);
        const res = await fetch("/api/questions/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            syllabusId: form.syllabusId,
            examId: exam.id,
            type: "MCQ",
            count: parseInt(form.mcqCount),
            difficulty: form.difficulty,
          }),
        });
        if (!res.ok) {
          const data = await res.json().catch(() => ({}));
          throw new Error(data.error || "Failed to generate MCQ questions");
        }
        addLog(`✅ ${form.mcqCount} MCQ questions generated`);
      }

      // Step 3: Generate coding questions
      if (parseInt(form.codingCount) > 0) {
        addLog(`🤖 Generating ${form.codingCount} coding problems...`);
        const res = await fetch("/api/questions/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            syllabusId: form.syllabusId,
            examId: exam.id,
            type: "CODING",
            count: parseInt(form.codingCount),
            difficulty: form.difficulty,
          }),
        });
        if (!res.ok) {
          const data = await res.json().catch(() => ({}));
          throw new Error(data.error || "Failed to generate coding questions");
        }
        addLog(`✅ ${form.codingCount} coding questions generated`);
      }

      addLog("🎉 Exam is ready!");
      setStep("done");
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Something went wrong during generation. Check Vercel logs.");
      setStep("form");
    }
  };

  if (step === "done") {
    return (
      <div className="flex min-h-screen">
        <Sidebar role="ADMIN" userName="Admin" />
        <main className="flex-1 flex items-center justify-center p-8">
          <div className="glass p-10 text-center max-w-md w-full">
            <CheckCircle size={56} className="text-green-400 mx-auto mb-4" />
            <h2 className="text-2xl font-bold mb-2">Exam Created!</h2>
            <p className="text-slate-400 mb-6">Questions generated by Gemini AI and saved to DB.</p>
            <div className="bg-[#0d1117] rounded-xl p-4 mb-6 text-left">
              {log.map((l, i) => <p key={i} className="text-xs text-green-400 py-0.5">{l}</p>)}
            </div>
            <button onClick={() => router.push("/admin/dashboard")} className="btn-primary w-full justify-center">
              Back to Dashboard
            </button>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="flex min-h-screen">
      <Sidebar role="ADMIN" userName="Admin" />
      <main className="flex-1 p-8 overflow-auto max-w-3xl">
        <div className="mb-8">
          <h1 className="text-3xl font-bold">Create New Exam</h1>
          <p className="text-slate-400 mt-1">Configure your exam. AI generates questions automatically.</p>
        </div>

        {step === "generating" ? (
          <div className="glass p-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 rounded-xl bg-blue-500/10 flex items-center justify-center">
                <Brain size={20} className="text-blue-400" />
              </div>
              <div>
                <h2 className="font-semibold">Gemini AI is generating questions...</h2>
                <p className="text-slate-400 text-sm">This takes about 15-30 seconds</p>
              </div>
            </div>
            <div className="bg-[#0d1117] rounded-xl p-4 space-y-1 min-h-32">
              {log.map((l, i) => (
                <p key={i} className="text-sm text-green-400 font-code">{l}</p>
              ))}
              <div className="flex items-center gap-2 text-slate-400 text-sm">
                <Loader2 size={12} className="animate-spin" /> Processing...
              </div>
            </div>
          </div>
        ) : (
          <form onSubmit={handleCreate} className="glass p-8 space-y-5">
            {error && <div className="bg-red-500/10 border border-red-500/30 text-red-400 px-4 py-3 rounded-xl text-sm">{error}</div>}

            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2">Exam Title</label>
              <input type="text" value={form.title} onChange={(e) => setForm((f) => ({ ...f, title: e.target.value }))}
                placeholder="e.g. Data Structures Final Exam" className="input-field" required />
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2">Select Syllabus</label>
              {syllabi.length === 0 ? (
                <div className="p-4 rounded-xl bg-yellow-500/10 border border-yellow-500/30 text-yellow-400 text-sm">
                  No syllabi found.{" "}
                  <a href="/admin/syllabus" className="underline">Add one first →</a>
                </div>
              ) : (
                <select value={form.syllabusId} onChange={(e) => setForm((f) => ({ ...f, syllabusId: e.target.value }))}
                  className="input-field" required>
                  <option value="">Choose a syllabus...</option>
                  {syllabi.map((s: any) => (
                    <option key={s.id} value={s.id}>{s.title} ({s.subject})</option>
                  ))}
                </select>
              )}
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">Duration (minutes)</label>
                <input type="number" value={form.duration} onChange={(e) => setForm((f) => ({ ...f, duration: e.target.value }))}
                  min="10" max="300" className="input-field" required />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-2">Scheduled Date & Time</label>
                <input type="datetime-local" value={form.scheduledAt} onChange={(e) => setForm((f) => ({ ...f, scheduledAt: e.target.value }))}
                  className="input-field" required />
              </div>
            </div>

            <div className="p-4 bg-blue-500/5 border border-blue-500/20 rounded-xl space-y-4">
              <p className="text-sm font-medium text-blue-400 flex items-center gap-2"><Brain size={14} /> AI Question Generation</p>
              <div className="grid grid-cols-3 gap-4">
                <div>
                  <label className="block text-xs text-slate-400 mb-1.5">MCQ Questions</label>
                  <input type="number" value={form.mcqCount} onChange={(e) => setForm((f) => ({ ...f, mcqCount: e.target.value }))}
                    min="0" max="20" className="input-field text-sm" />
                </div>
                <div>
                  <label className="block text-xs text-slate-400 mb-1.5">Coding Problems</label>
                  <input type="number" value={form.codingCount} onChange={(e) => setForm((f) => ({ ...f, codingCount: e.target.value }))}
                    min="0" max="10" className="input-field text-sm" />
                </div>
                <div>
                  <label className="block text-xs text-slate-400 mb-1.5">Difficulty</label>
                  <select value={form.difficulty} onChange={(e) => setForm((f) => ({ ...f, difficulty: e.target.value }))} className="input-field text-sm">
                    <option value="easy">Easy</option>
                    <option value="medium">Medium</option>
                    <option value="hard">Hard</option>
                  </select>
                </div>
              </div>
            </div>

            <button type="submit" className="btn-primary w-full justify-center">
              <Brain size={16} /> Generate Exam with AI
            </button>
          </form>
        )}
      </main>
    </div>
  );
}

